version: '3.8'

services:
  frontend:
    build:
      context: ./frontend  # Ruta correcta para tu directorio frontend
    ports:
      - "3000:3000"  # Exponer el puerto del frontend
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend  # Ruta correcta para tu directorio backend
    ports:
      - "8080:8080"  # Exponer el puerto del backend
    environment:
      - NODE_ENV=production
      - DATABASE_URL="mysql://root:example_password@db:3306/app_db"  # Configuración de la base de datos MySQL
    depends_on:
      - db  # Asegura que el backend dependa de la base de datos
    networks:
      - app-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: app_db
    ports:
      - "3306:3306"  # Exponer el puerto de MySQL
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

