version: '3.8'

services:
  frontend:
    build:
      context: ./frontend  # Ruta corregida: ya estás dentro de mi-crud-app
    ports:
      - "3000:3000"  # Exponer el puerto del frontend
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend  # Ruta corregida al Dockerfile del backend
    ports:
      - "8080:8080"  # Exponer el puerto del backend
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: app_db
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
