version: '3.8'

services:
  frontend:
    build:
      context: ./frontend  # Ruta correcta para tu directorio frontend
    ports:
      - "3000:3000"  # Exponer el puerto del frontend
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend  # Ruta correcta para tu directorio backend
    ports:
      - "8080:8080"  # Exponer el puerto del backend
    environment:
      - NODE_ENV=production
      - DATABASE_URL="postgresql://postgres:1234@db:5432/crud_express4"  # Configuración de la base de datos PostgreSQL
    depends_on:
      - db  # Asegura que el backend dependa de la base de datos
    networks:
      - app-network

  db:
    image: postgres:latest  # Usar la imagen oficial de PostgreSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: crud_express4
    ports:
      - "5432:5432"  # Exponer el puerto de PostgreSQL
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

