pipeline {
  agent any

  environment {
    COMPOSE_FILE = 'docker-compose.yml'
  }

  stages {
    stage('Checkout') {
      steps {
        echo 'Clonando el repositorio...'
        checkout scm
      }
    }

    stage('Build & Deploy') {
      steps {
        echo 'Levantando contenedores con Docker Compose...'
        sh 'docker-compose down'
        sh 'docker-compose up --build -d'
      }
    }

    stage('Verificar servicios') {
      steps {
        sh 'docker ps'
      }
    }
  }

  post {
    always {
      echo 'Proceso finalizado. Revisa el estado arriba.'
    }
  }
}
